name: Add Channel

on:
  repository_dispatch:
    types: [add_channel]

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update novaplay.json
        run: |

          python <<EOF

          import json

          FILE = "novaplay.json"

          with open(FILE, "r", encoding="utf8") as f:
              data = json.load(f)

          payload = "${{ github.event.client_payload }}"

          category = "${{ github.event.client_payload.category }}"
          name = "${{ github.event.client_payload.name }}"
          url = "${{ github.event.client_payload.url }}"
          logo = "${{ github.event.client_payload.logo }}"
          info = "${{ github.event.client_payload.info }}"
          texto = "${{ github.event.client_payload.texto }}"
          nsfw = "${{ github.event.client_payload.nsfw }}"

          protection = "${{ github.event.client_payload.protection }}"
          referer = "${{ github.event.client_payload.referer }}"
          drm_type = "${{ github.event.client_payload.drmType }}"
          license_uri = "${{ github.event.client_payload.license }}"

          new_channel = {
              "name": name,
              "url": url,
              "logo": logo
          }

          if info:
              new_channel["info"] = info

          if texto:
              new_channel["texto"] = texto

          if nsfw == "yes":
              new_channel["nsfw"] = "yes"

          if protection == "yes":
              if referer:
                  new_channel["referer"] = referer
              if drm_type:
                  new_channel["type"] = drm_type
              if license_uri:
                  new_channel["drm_license_uri"] = license_uri

          # buscar categoría
          found = False

          for item in data:
              if item.get("type") == "category" and item.get("name") == category:

                  item.setdefault("channels", [])

                  if not any(ch.get("url") == url for ch in item["channels"]):
                      item["channels"].append(new_channel)

                  found = True
                  break

          # si no existe crearla
          if not found:
              data.append({
                  "name": category,
                  "type": "category",
                  "channels": [new_channel]
              })

          with open(FILE, "w", encoding="utf8") as f:
              json.dump(data, f, indent=2, ensure_ascii=False)

          EOF

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add novaplay.json
          git commit -m "Add channel" || exit 0
          git push
