name: AUTOUPDATE

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  autoupdate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Requests
        run: pip install requests

      - name: Ejecutar AUTOUPDATE
        run: python AUTOUPDATE.py

      - name: Commit automático
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add novaplay.json

          git diff --cached --quiet || (
            git commit -m "AUTOUPDATE"
            git push
          )
