name: Sync ccur-session

permissions:
  contents: write

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run update
        run: python update.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add novaplay.json

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "update ccur-session"
          git push
