name: Mirror Repo

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo original como mirror
        run: |
          git clone --mirror https://github.com/ThedarkSoldier996/test.git
          cd test.git
          git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hanknova/novaplay.git
          git push --mirror
