name: Mirror Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        shell: bash
        run: |
          git clone --mirror https://github.com/ThedarkSoldier996/test.git
          cd test.git

          # Eliminar referencias de Pull Requests que GitHub no permite subir
          git for-each-ref --format='%(refname)' refs/pull | while read ref; do
            git update-ref -d "$ref"
          done

          git remote set-url --push origin https://${{ secrets.TOKEN }}@github.com/hanknova/novaplay.git

          git push --mirror
